continuous:
    - papyros/builder
    - papyros/libpapyros
    - iBeliever/Spoon-Knife
repositories:
    - name: papyros-testing
      git: papyros/repository#branch=testing
      export: /home/mspencer/repos/papyros-testing
ostree:
    - name: testing
      git: papyros/repository#branch=testing
isos:
    - name: testing
      git: papyros/repository#branch=testing
      config: iso_config.yml
