continuous:
    - papyros/builder
    - papyros/libpapyros
    - iBeliever/Spoon-Knife
repositories:
    - name: testing
      git: papyros/repository#branch=testing
ostree:
    - name: testing
      git: papyros/repository#branch=testing
isos:
    - name: testing
      git: papyros/repository#branch=testing
      config: iso_config.yml
